name: Sync to HuggingFace hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_URL: ${{ secrets.LLM_URL }}
          LLM_TYPE: ${{ secrets.LLM_TYPE }}
          LLM_NAME: ${{ secrets.LLM_NAME }}
          STT_URL: ${{ secrets.STT_URL }}
          STT_TYPE: ${{ secrets.STT_TYPE }}
          STT_NAME: ${{ secrets.STT_NAME }}
          TTS_URL: ${{ secrets.TTS_URL }}
          TTS_TYPE: ${{ secrets.TTS_TYPE }}
          TTS_NAME: ${{ secrets.TTS_NAME }}
        run: python test.py

      - name: Push to hub
        if: success()
        env:
          HF_TOKEN: ${{ secrets.HF_API_KEY }}
        run: |
          git push https://IliaLarchenko:$HF_TOKEN@huggingface.co/spaces/IliaLarchenko/interviewer main
